# Generated by Django 4.2.3 on 2023-08-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_meta_alter_advertisement_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
